//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.ENTITYMODELS.DATA
{
    using System;
    
    public partial class WEB_CARONLINE_SP_TypeOfCar_GetAll2_Result
    {
        public System.Guid TypeOfCarID { get; set; }
        public string TypeName { get; set; }
        public string CompanyName { get; set; }
        public string DesignName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
