//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.ENTITYMODELS.DATA
{
    using System;
    
    public partial class WEB_CARONLINE_SP_GearCar_GetByID_Result
    {
        public System.Guid CarGearId { get; set; }
        public string CarGearName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
