//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.ENTITYMODELS.DATA
{
    using System;
    
    public partial class WEB_CARONLINE_SP_Image_GetFirstOfPost_Result
    {
        public System.Guid PostImageID { get; set; }
        public Nullable<System.Guid> PostID { get; set; }
        public string ImageName { get; set; }
        public string ImageAlt { get; set; }
        public Nullable<byte> Rank { get; set; }
    }
}
