//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.ENTITYMODELS.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarOnlineEntities : DbContext
    {
        public CarOnlineEntities()
            : base("name=CarOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Account_CheckLogin_Result> WEB_CARONLINE_SP_Account_CheckLogin(string username, string passWords)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passWordsParameter = passWords != null ?
                new ObjectParameter("PassWords", passWords) :
                new ObjectParameter("PassWords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Account_CheckLogin_Result>("WEB_CARONLINE_SP_Account_CheckLogin", usernameParameter, passWordsParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Account_CheckUserName_Result> WEB_CARONLINE_SP_Account_CheckUserName(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Account_CheckUserName_Result>("WEB_CARONLINE_SP_Account_CheckUserName", usernameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Account_Delete(Nullable<System.Guid> accountID)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Account_Delete", accountIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Account_GetAll_Result> WEB_CARONLINE_SP_Account_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Account_GetAll_Result>("WEB_CARONLINE_SP_Account_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Account_GetById_Result> WEB_CARONLINE_SP_Account_GetById(Nullable<System.Guid> accountID)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Account_GetById_Result>("WEB_CARONLINE_SP_Account_GetById", accountIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Account_Insert(Nullable<System.Guid> accountID, Nullable<byte> roleID, string iD_Facebook, string iD_Gmail, string userName, string password, string avatar, string fullName, Nullable<int> numberOfLikeProfile, Nullable<int> numberOfPost, Nullable<int> numberOfFlow, Nullable<int> numberOfComment, string mobile, Nullable<bool> active, Nullable<System.DateTime> birthDay, Nullable<System.DateTime> joinDay, string email, string address, Nullable<bool> isdeleted)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(byte));
    
            var iD_FacebookParameter = iD_Facebook != null ?
                new ObjectParameter("ID_Facebook", iD_Facebook) :
                new ObjectParameter("ID_Facebook", typeof(string));
    
            var iD_GmailParameter = iD_Gmail != null ?
                new ObjectParameter("ID_Gmail", iD_Gmail) :
                new ObjectParameter("ID_Gmail", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("Avatar", avatar) :
                new ObjectParameter("Avatar", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var numberOfLikeProfileParameter = numberOfLikeProfile.HasValue ?
                new ObjectParameter("NumberOfLikeProfile", numberOfLikeProfile) :
                new ObjectParameter("NumberOfLikeProfile", typeof(int));
    
            var numberOfPostParameter = numberOfPost.HasValue ?
                new ObjectParameter("NumberOfPost", numberOfPost) :
                new ObjectParameter("NumberOfPost", typeof(int));
    
            var numberOfFlowParameter = numberOfFlow.HasValue ?
                new ObjectParameter("NumberOfFlow", numberOfFlow) :
                new ObjectParameter("NumberOfFlow", typeof(int));
    
            var numberOfCommentParameter = numberOfComment.HasValue ?
                new ObjectParameter("NumberOfComment", numberOfComment) :
                new ObjectParameter("NumberOfComment", typeof(int));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var birthDayParameter = birthDay.HasValue ?
                new ObjectParameter("BirthDay", birthDay) :
                new ObjectParameter("BirthDay", typeof(System.DateTime));
    
            var joinDayParameter = joinDay.HasValue ?
                new ObjectParameter("JoinDay", joinDay) :
                new ObjectParameter("JoinDay", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Account_Insert", accountIDParameter, roleIDParameter, iD_FacebookParameter, iD_GmailParameter, userNameParameter, passwordParameter, avatarParameter, fullNameParameter, numberOfLikeProfileParameter, numberOfPostParameter, numberOfFlowParameter, numberOfCommentParameter, mobileParameter, activeParameter, birthDayParameter, joinDayParameter, emailParameter, addressParameter, isdeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Account_Update(Nullable<System.Guid> accountID, Nullable<byte> roleID, string iD_Facebook, string iD_Gmail, string userName, string password, string avatar, string fullName, Nullable<int> numberOfLikeProfile, Nullable<int> numberOfPost, Nullable<int> numberOfFlow, Nullable<int> numberOfComment, string mobile, Nullable<bool> active, Nullable<System.DateTime> birthDay, Nullable<System.DateTime> joinDay, string email, string address, Nullable<bool> isdeleted)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(byte));
    
            var iD_FacebookParameter = iD_Facebook != null ?
                new ObjectParameter("ID_Facebook", iD_Facebook) :
                new ObjectParameter("ID_Facebook", typeof(string));
    
            var iD_GmailParameter = iD_Gmail != null ?
                new ObjectParameter("ID_Gmail", iD_Gmail) :
                new ObjectParameter("ID_Gmail", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("Avatar", avatar) :
                new ObjectParameter("Avatar", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var numberOfLikeProfileParameter = numberOfLikeProfile.HasValue ?
                new ObjectParameter("NumberOfLikeProfile", numberOfLikeProfile) :
                new ObjectParameter("NumberOfLikeProfile", typeof(int));
    
            var numberOfPostParameter = numberOfPost.HasValue ?
                new ObjectParameter("NumberOfPost", numberOfPost) :
                new ObjectParameter("NumberOfPost", typeof(int));
    
            var numberOfFlowParameter = numberOfFlow.HasValue ?
                new ObjectParameter("NumberOfFlow", numberOfFlow) :
                new ObjectParameter("NumberOfFlow", typeof(int));
    
            var numberOfCommentParameter = numberOfComment.HasValue ?
                new ObjectParameter("NumberOfComment", numberOfComment) :
                new ObjectParameter("NumberOfComment", typeof(int));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var birthDayParameter = birthDay.HasValue ?
                new ObjectParameter("BirthDay", birthDay) :
                new ObjectParameter("BirthDay", typeof(System.DateTime));
    
            var joinDayParameter = joinDay.HasValue ?
                new ObjectParameter("JoinDay", joinDay) :
                new ObjectParameter("JoinDay", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Account_Update", accountIDParameter, roleIDParameter, iD_FacebookParameter, iD_GmailParameter, userNameParameter, passwordParameter, avatarParameter, fullNameParameter, numberOfLikeProfileParameter, numberOfPostParameter, numberOfFlowParameter, numberOfCommentParameter, mobileParameter, activeParameter, birthDayParameter, joinDayParameter, emailParameter, addressParameter, isdeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CarStatus_DELETE(Nullable<System.Guid> carStatusID)
        {
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CarStatus_DELETE", carStatusIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_CarStatus_GetAll_Result> WEB_CARONLINE_SP_CarStatus_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_CarStatus_GetAll_Result>("WEB_CARONLINE_SP_CarStatus_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_CarStatus_GetByID_Result> WEB_CARONLINE_SP_CarStatus_GetByID(Nullable<System.Guid> carStatusID)
        {
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_CarStatus_GetByID_Result>("WEB_CARONLINE_SP_CarStatus_GetByID", carStatusIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CarStatus_INSERT(Nullable<System.Guid> carStatusID, string carStatusName)
        {
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            var carStatusNameParameter = carStatusName != null ?
                new ObjectParameter("CarStatusName", carStatusName) :
                new ObjectParameter("CarStatusName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CarStatus_INSERT", carStatusIDParameter, carStatusNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CarStatus_UPDATE(Nullable<System.Guid> carStatusID, string carStatusName)
        {
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            var carStatusNameParameter = carStatusName != null ?
                new ObjectParameter("CarStatusName", carStatusName) :
                new ObjectParameter("CarStatusName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CarStatus_UPDATE", carStatusIDParameter, carStatusNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_City_Delete(Nullable<System.Guid> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_City_Delete", cityIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_City_GetAll_Result> WEB_CARONLINE_SP_City_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_City_GetAll_Result>("WEB_CARONLINE_SP_City_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_City_GetByID_Result> WEB_CARONLINE_SP_City_GetByID(Nullable<System.Guid> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_City_GetByID_Result>("WEB_CARONLINE_SP_City_GetByID", cityIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_City_InSert(Nullable<System.Guid> cityId, string cityName, Nullable<System.Guid> regionId, Nullable<bool> isDeleted)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(System.Guid));
    
            var cityNameParameter = cityName != null ?
                new ObjectParameter("CityName", cityName) :
                new ObjectParameter("CityName", typeof(string));
    
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_City_InSert", cityIdParameter, cityNameParameter, regionIdParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_City_Update(Nullable<System.Guid> cityId, string cityName, Nullable<System.Guid> regionId, Nullable<bool> isDeleted)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(System.Guid));
    
            var cityNameParameter = cityName != null ?
                new ObjectParameter("CityName", cityName) :
                new ObjectParameter("CityName", typeof(string));
    
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_City_Update", cityIdParameter, cityNameParameter, regionIdParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CompanyCar_DELETE(Nullable<System.Guid> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CompanyCar_DELETE", companyIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_CompanyCar_GetAll_Result> WEB_CARONLINE_SP_CompanyCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_CompanyCar_GetAll_Result>("WEB_CARONLINE_SP_CompanyCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_CompanyCar_GetByID_Result> WEB_CARONLINE_SP_CompanyCar_GetByID(Nullable<System.Guid> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_CompanyCar_GetByID_Result>("WEB_CARONLINE_SP_CompanyCar_GetByID", companyIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CompanyCar_INSERT(Nullable<System.Guid> companyID, string companyName, Nullable<bool> status, string description)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CompanyCar_INSERT", companyIDParameter, companyNameParameter, statusParameter, descriptionParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_CompanyCar_UPDATE(Nullable<System.Guid> companyID, string companyName, Nullable<bool> status, string description)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_CompanyCar_UPDATE", companyIDParameter, companyNameParameter, statusParameter, descriptionParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DesignCar_DELETE(Nullable<System.Guid> designId)
        {
            var designIdParameter = designId.HasValue ?
                new ObjectParameter("DesignId", designId) :
                new ObjectParameter("DesignId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DesignCar_DELETE", designIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DesignCar_GetAll_Result> WEB_CARONLINE_SP_DesignCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DesignCar_GetAll_Result>("WEB_CARONLINE_SP_DesignCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DesignCar_GetByID_Result> WEB_CARONLINE_SP_DesignCar_GetByID(Nullable<System.Guid> designId)
        {
            var designIdParameter = designId.HasValue ?
                new ObjectParameter("DesignId", designId) :
                new ObjectParameter("DesignId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DesignCar_GetByID_Result>("WEB_CARONLINE_SP_DesignCar_GetByID", designIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DesignCar_INSERT(Nullable<System.Guid> designId, string designName)
        {
            var designIdParameter = designId.HasValue ?
                new ObjectParameter("DesignId", designId) :
                new ObjectParameter("DesignId", typeof(System.Guid));
    
            var designNameParameter = designName != null ?
                new ObjectParameter("DesignName", designName) :
                new ObjectParameter("DesignName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DesignCar_INSERT", designIdParameter, designNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DesignCar_UPDATE(Nullable<System.Guid> designId, string designName)
        {
            var designIdParameter = designId.HasValue ?
                new ObjectParameter("DesignId", designId) :
                new ObjectParameter("DesignId", typeof(System.Guid));
    
            var designNameParameter = designName != null ?
                new ObjectParameter("DesignName", designName) :
                new ObjectParameter("DesignName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DesignCar_UPDATE", designIdParameter, designNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DigitalCategory_Delete(Nullable<System.Guid> digitalCategoryId)
        {
            var digitalCategoryIdParameter = digitalCategoryId.HasValue ?
                new ObjectParameter("DigitalCategoryId", digitalCategoryId) :
                new ObjectParameter("DigitalCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DigitalCategory_Delete", digitalCategoryIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DigitalCategory_GetAll_Result> WEB_CARONLINE_SP_DigitalCategory_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DigitalCategory_GetAll_Result>("WEB_CARONLINE_SP_DigitalCategory_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DigitalCategory_GetById_Result> WEB_CARONLINE_SP_DigitalCategory_GetById(Nullable<System.Guid> digitalCategoryId)
        {
            var digitalCategoryIdParameter = digitalCategoryId.HasValue ?
                new ObjectParameter("DigitalCategoryId", digitalCategoryId) :
                new ObjectParameter("DigitalCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DigitalCategory_GetById_Result>("WEB_CARONLINE_SP_DigitalCategory_GetById", digitalCategoryIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DigitalCategory_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> digitalCategoryId, string digitalCategoryName)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var digitalCategoryIdParameter = digitalCategoryId.HasValue ?
                new ObjectParameter("DigitalCategoryId", digitalCategoryId) :
                new ObjectParameter("DigitalCategoryId", typeof(System.Guid));
    
            var digitalCategoryNameParameter = digitalCategoryName != null ?
                new ObjectParameter("DigitalCategoryName", digitalCategoryName) :
                new ObjectParameter("DigitalCategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DigitalCategory_InsertOrUpdate", flagParameter, digitalCategoryIdParameter, digitalCategoryNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DigitalDetail_Delete(Nullable<System.Guid> degitalDetailId)
        {
            var degitalDetailIdParameter = degitalDetailId.HasValue ?
                new ObjectParameter("DegitalDetailId", degitalDetailId) :
                new ObjectParameter("DegitalDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DigitalDetail_Delete", degitalDetailIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DigitalDetail_GetAll_Result> WEB_CARONLINE_SP_DigitalDetail_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DigitalDetail_GetAll_Result>("WEB_CARONLINE_SP_DigitalDetail_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_DigitalDetail_GetById_Result> WEB_CARONLINE_SP_DigitalDetail_GetById(Nullable<System.Guid> digitalDetailId)
        {
            var digitalDetailIdParameter = digitalDetailId.HasValue ?
                new ObjectParameter("DigitalDetailId", digitalDetailId) :
                new ObjectParameter("DigitalDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_DigitalDetail_GetById_Result>("WEB_CARONLINE_SP_DigitalDetail_GetById", digitalDetailIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_DigitalDetail_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> digitalDetailId, Nullable<System.Guid> postId, Nullable<System.Guid> digitalCategoryId, Nullable<bool> applyed, Nullable<bool> isDeleted)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var digitalDetailIdParameter = digitalDetailId.HasValue ?
                new ObjectParameter("DigitalDetailId", digitalDetailId) :
                new ObjectParameter("DigitalDetailId", typeof(System.Guid));
    
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            var digitalCategoryIdParameter = digitalCategoryId.HasValue ?
                new ObjectParameter("DigitalCategoryId", digitalCategoryId) :
                new ObjectParameter("DigitalCategoryId", typeof(System.Guid));
    
            var applyedParameter = applyed.HasValue ?
                new ObjectParameter("Applyed", applyed) :
                new ObjectParameter("Applyed", typeof(bool));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_DigitalDetail_InsertOrUpdate", flagParameter, digitalDetailIdParameter, postIdParameter, digitalCategoryIdParameter, applyedParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_ExteriorFurnitureColor_DELETE(Nullable<System.Guid> exteriorFurnitureColorID)
        {
            var exteriorFurnitureColorIDParameter = exteriorFurnitureColorID.HasValue ?
                new ObjectParameter("ExteriorFurnitureColorID", exteriorFurnitureColorID) :
                new ObjectParameter("ExteriorFurnitureColorID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_ExteriorFurnitureColor_DELETE", exteriorFurnitureColorIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_ExteriorFurnitureColor_GetAll_Result> WEB_CARONLINE_SP_ExteriorFurnitureColor_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_ExteriorFurnitureColor_GetAll_Result>("WEB_CARONLINE_SP_ExteriorFurnitureColor_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_ExteriorFurnitureColor_GetByID_Result> WEB_CARONLINE_SP_ExteriorFurnitureColor_GetByID(Nullable<System.Guid> exteriorFurnitureColorID)
        {
            var exteriorFurnitureColorIDParameter = exteriorFurnitureColorID.HasValue ?
                new ObjectParameter("ExteriorFurnitureColorID", exteriorFurnitureColorID) :
                new ObjectParameter("ExteriorFurnitureColorID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_ExteriorFurnitureColor_GetByID_Result>("WEB_CARONLINE_SP_ExteriorFurnitureColor_GetByID", exteriorFurnitureColorIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_ExteriorFurnitureColor_INSERT(Nullable<System.Guid> exteriorFurnitureColorID, string exteriorFurnitureColorName)
        {
            var exteriorFurnitureColorIDParameter = exteriorFurnitureColorID.HasValue ?
                new ObjectParameter("ExteriorFurnitureColorID", exteriorFurnitureColorID) :
                new ObjectParameter("ExteriorFurnitureColorID", typeof(System.Guid));
    
            var exteriorFurnitureColorNameParameter = exteriorFurnitureColorName != null ?
                new ObjectParameter("ExteriorFurnitureColorName", exteriorFurnitureColorName) :
                new ObjectParameter("ExteriorFurnitureColorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_ExteriorFurnitureColor_INSERT", exteriorFurnitureColorIDParameter, exteriorFurnitureColorNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_ExteriorFurnitureColor_UPDATE(Nullable<System.Guid> exteriorFurnitureColorID, string exteriorFurnitureColorName)
        {
            var exteriorFurnitureColorIDParameter = exteriorFurnitureColorID.HasValue ?
                new ObjectParameter("ExteriorFurnitureColorID", exteriorFurnitureColorID) :
                new ObjectParameter("ExteriorFurnitureColorID", typeof(System.Guid));
    
            var exteriorFurnitureColorNameParameter = exteriorFurnitureColorName != null ?
                new ObjectParameter("ExteriorFurnitureColorName", exteriorFurnitureColorName) :
                new ObjectParameter("ExteriorFurnitureColorName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_ExteriorFurnitureColor_UPDATE", exteriorFurnitureColorIDParameter, exteriorFurnitureColorNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_FuelCar_DELETE(Nullable<System.Guid> fuelID)
        {
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_FuelCar_DELETE", fuelIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_FuelCar_GetAll_Result> WEB_CARONLINE_SP_FuelCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_FuelCar_GetAll_Result>("WEB_CARONLINE_SP_FuelCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_FuelCar_GetByID_Result> WEB_CARONLINE_SP_FuelCar_GetByID(Nullable<System.Guid> fuelID)
        {
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_FuelCar_GetByID_Result>("WEB_CARONLINE_SP_FuelCar_GetByID", fuelIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_FuelCar_INSERT(Nullable<System.Guid> fuelID, string fuelName)
        {
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            var fuelNameParameter = fuelName != null ?
                new ObjectParameter("FuelName", fuelName) :
                new ObjectParameter("FuelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_FuelCar_INSERT", fuelIDParameter, fuelNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_FuelCar_UPDATE(Nullable<System.Guid> fuelID, string fuelName)
        {
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            var fuelNameParameter = fuelName != null ?
                new ObjectParameter("FuelName", fuelName) :
                new ObjectParameter("FuelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_FuelCar_UPDATE", fuelIDParameter, fuelNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_GearCar_DELETE(Nullable<System.Guid> carGearId)
        {
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_GearCar_DELETE", carGearIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_GearCar_GetAll_Result> WEB_CARONLINE_SP_GearCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_GearCar_GetAll_Result>("WEB_CARONLINE_SP_GearCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_GearCar_GetByID_Result> WEB_CARONLINE_SP_GearCar_GetByID(Nullable<System.Guid> carGearId)
        {
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_GearCar_GetByID_Result>("WEB_CARONLINE_SP_GearCar_GetByID", carGearIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_GearCar_INSERT(Nullable<System.Guid> carGearId, string carGearName)
        {
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            var carGearNameParameter = carGearName != null ?
                new ObjectParameter("CarGearName", carGearName) :
                new ObjectParameter("CarGearName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_GearCar_INSERT", carGearIdParameter, carGearNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_GearCar_UPDATE(Nullable<System.Guid> carGearId, string carGearName)
        {
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            var carGearNameParameter = carGearName != null ?
                new ObjectParameter("CarGearName", carGearName) :
                new ObjectParameter("CarGearName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_GearCar_UPDATE", carGearIdParameter, carGearNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_MadeInCar_Delete(Nullable<System.Guid> madeInID)
        {
            var madeInIDParameter = madeInID.HasValue ?
                new ObjectParameter("MadeInID", madeInID) :
                new ObjectParameter("MadeInID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_MadeInCar_Delete", madeInIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_MadeInCar_GetAll_Result> WEB_CARONLINE_SP_MadeInCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_MadeInCar_GetAll_Result>("WEB_CARONLINE_SP_MadeInCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_MadeInCar_GetByID_Result> WEB_CARONLINE_SP_MadeInCar_GetByID(Nullable<System.Guid> madeInID)
        {
            var madeInIDParameter = madeInID.HasValue ?
                new ObjectParameter("MadeInID", madeInID) :
                new ObjectParameter("MadeInID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_MadeInCar_GetByID_Result>("WEB_CARONLINE_SP_MadeInCar_GetByID", madeInIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_MadeInCar_InSert(Nullable<System.Guid> madeInID, string madeInName, Nullable<bool> isDeleted)
        {
            var madeInIDParameter = madeInID.HasValue ?
                new ObjectParameter("MadeInID", madeInID) :
                new ObjectParameter("MadeInID", typeof(System.Guid));
    
            var madeInNameParameter = madeInName != null ?
                new ObjectParameter("MadeInName", madeInName) :
                new ObjectParameter("MadeInName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_MadeInCar_InSert", madeInIDParameter, madeInNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_MadeInCar_Update(Nullable<System.Guid> madeInID, string madeInName, Nullable<bool> isDeleted)
        {
            var madeInIDParameter = madeInID.HasValue ?
                new ObjectParameter("MadeInID", madeInID) :
                new ObjectParameter("MadeInID", typeof(System.Guid));
    
            var madeInNameParameter = madeInName != null ?
                new ObjectParameter("MadeInName", madeInName) :
                new ObjectParameter("MadeInName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_MadeInCar_Update", madeInIDParameter, madeInNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfDoor_Delete(Nullable<System.Guid> numberOfDoorId)
        {
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfDoor_Delete", numberOfDoorIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_NumberOfDoor_GetAll_Result> WEB_CARONLINE_SP_NumberOfDoor_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_NumberOfDoor_GetAll_Result>("WEB_CARONLINE_SP_NumberOfDoor_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_NumberOfDoor_GetByID_Result> WEB_CARONLINE_SP_NumberOfDoor_GetByID(Nullable<System.Guid> numberOfDoorId)
        {
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_NumberOfDoor_GetByID_Result>("WEB_CARONLINE_SP_NumberOfDoor_GetByID", numberOfDoorIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfDoor_InSert(Nullable<System.Guid> numberOfDoorId, string numberOfDoorName, Nullable<bool> isDeleted)
        {
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            var numberOfDoorNameParameter = numberOfDoorName != null ?
                new ObjectParameter("NumberOfDoorName", numberOfDoorName) :
                new ObjectParameter("NumberOfDoorName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfDoor_InSert", numberOfDoorIdParameter, numberOfDoorNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfDoor_Update(Nullable<System.Guid> numberOfDoorId, string numberOfDoorName, Nullable<bool> isDeleted)
        {
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            var numberOfDoorNameParameter = numberOfDoorName != null ?
                new ObjectParameter("NumberOfDoorName", numberOfDoorName) :
                new ObjectParameter("NumberOfDoorName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfDoor_Update", numberOfDoorIdParameter, numberOfDoorNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfSeat_Delete(Nullable<System.Guid> numberOfSeatId)
        {
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfSeat_Delete", numberOfSeatIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_NumberOfSeat_GetAll_Result> WEB_CARONLINE_SP_NumberOfSeat_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_NumberOfSeat_GetAll_Result>("WEB_CARONLINE_SP_NumberOfSeat_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_NumberOfSeat_GetByID_Result> WEB_CARONLINE_SP_NumberOfSeat_GetByID(Nullable<System.Guid> numberOfSeatId)
        {
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_NumberOfSeat_GetByID_Result>("WEB_CARONLINE_SP_NumberOfSeat_GetByID", numberOfSeatIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfSeat_InSert(Nullable<System.Guid> numberOfSeatId, string numberOfSeatName, Nullable<bool> isDeleted)
        {
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            var numberOfSeatNameParameter = numberOfSeatName != null ?
                new ObjectParameter("NumberOfSeatName", numberOfSeatName) :
                new ObjectParameter("NumberOfSeatName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfSeat_InSert", numberOfSeatIdParameter, numberOfSeatNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_NumberOfSeat_Update(Nullable<System.Guid> numberOfSeatId, string numberOfSeatName, Nullable<bool> isDeleted)
        {
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            var numberOfSeatNameParameter = numberOfSeatName != null ?
                new ObjectParameter("NumberOfSeatName", numberOfSeatName) :
                new ObjectParameter("NumberOfSeatName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_NumberOfSeat_Update", numberOfSeatIdParameter, numberOfSeatNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Region_Delete(Nullable<System.Guid> regionId)
        {
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Region_Delete", regionIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Region_GetAll_Result> WEB_CARONLINE_SP_Region_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Region_GetAll_Result>("WEB_CARONLINE_SP_Region_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Region_GetByID_Result> WEB_CARONLINE_SP_Region_GetByID(Nullable<System.Guid> regionId)
        {
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Region_GetByID_Result>("WEB_CARONLINE_SP_Region_GetByID", regionIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Region_InSert(Nullable<System.Guid> regionId, string regionName, Nullable<bool> isDeleted)
        {
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            var regionNameParameter = regionName != null ?
                new ObjectParameter("RegionName", regionName) :
                new ObjectParameter("RegionName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Region_InSert", regionIdParameter, regionNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Region_Update(Nullable<System.Guid> regionId, string regionName, Nullable<bool> isDeleted)
        {
            var regionIdParameter = regionId.HasValue ?
                new ObjectParameter("RegionId", regionId) :
                new ObjectParameter("RegionId", typeof(System.Guid));
    
            var regionNameParameter = regionName != null ?
                new ObjectParameter("RegionName", regionName) :
                new ObjectParameter("RegionName", typeof(string));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Region_Update", regionIdParameter, regionNameParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Role_Delete(Nullable<System.Guid> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Role_Delete", roleIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Role_GetAll_Result> WEB_CARONLINE_SP_Role_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Role_GetAll_Result>("WEB_CARONLINE_SP_Role_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Role_GetById_Result> WEB_CARONLINE_SP_Role_GetById(Nullable<byte> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Role_GetById_Result>("WEB_CARONLINE_SP_Role_GetById", roleIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Role_Insert(Nullable<byte> roleID, string roleName, Nullable<bool> status, Nullable<bool> isDeleted, string description)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(byte));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Role_Insert", roleIDParameter, roleNameParameter, statusParameter, isDeletedParameter, descriptionParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Role_Update(Nullable<byte> roleID, string roleName, Nullable<bool> status, Nullable<bool> isDeleted, string description)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(byte));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Role_Update", roleIDParameter, roleNameParameter, statusParameter, isDeletedParameter, descriptionParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SafeCategory_Delete(Nullable<System.Guid> safeCategoryId)
        {
            var safeCategoryIdParameter = safeCategoryId.HasValue ?
                new ObjectParameter("SafeCategoryId", safeCategoryId) :
                new ObjectParameter("SafeCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SafeCategory_Delete", safeCategoryIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SafeCategory_GetAll_Result> WEB_CARONLINE_SP_SafeCategory_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SafeCategory_GetAll_Result>("WEB_CARONLINE_SP_SafeCategory_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SafeCategory_GetById_Result> WEB_CARONLINE_SP_SafeCategory_GetById(Nullable<System.Guid> safeCategoryId)
        {
            var safeCategoryIdParameter = safeCategoryId.HasValue ?
                new ObjectParameter("SafeCategoryId", safeCategoryId) :
                new ObjectParameter("SafeCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SafeCategory_GetById_Result>("WEB_CARONLINE_SP_SafeCategory_GetById", safeCategoryIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SafeCategory_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> safeCategoryId, string safeCategoryName)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var safeCategoryIdParameter = safeCategoryId.HasValue ?
                new ObjectParameter("SafeCategoryId", safeCategoryId) :
                new ObjectParameter("SafeCategoryId", typeof(System.Guid));
    
            var safeCategoryNameParameter = safeCategoryName != null ?
                new ObjectParameter("SafeCategoryName", safeCategoryName) :
                new ObjectParameter("SafeCategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SafeCategory_InsertOrUpdate", flagParameter, safeCategoryIdParameter, safeCategoryNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SafeDetail_Delete(Nullable<System.Guid> safeDetailId)
        {
            var safeDetailIdParameter = safeDetailId.HasValue ?
                new ObjectParameter("SafeDetailId", safeDetailId) :
                new ObjectParameter("SafeDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SafeDetail_Delete", safeDetailIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SafeDetail_GetAll_Result> WEB_CARONLINE_SP_SafeDetail_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SafeDetail_GetAll_Result>("WEB_CARONLINE_SP_SafeDetail_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SafeDetail_GetById_Result> WEB_CARONLINE_SP_SafeDetail_GetById(Nullable<System.Guid> safeDetailId)
        {
            var safeDetailIdParameter = safeDetailId.HasValue ?
                new ObjectParameter("SafeDetailId", safeDetailId) :
                new ObjectParameter("SafeDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SafeDetail_GetById_Result>("WEB_CARONLINE_SP_SafeDetail_GetById", safeDetailIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SafeDetail_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> safeDetailId, Nullable<System.Guid> postId, Nullable<System.Guid> safeCategoryId, Nullable<bool> applyed, Nullable<bool> isDeleted)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var safeDetailIdParameter = safeDetailId.HasValue ?
                new ObjectParameter("SafeDetailId", safeDetailId) :
                new ObjectParameter("SafeDetailId", typeof(System.Guid));
    
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            var safeCategoryIdParameter = safeCategoryId.HasValue ?
                new ObjectParameter("SafeCategoryId", safeCategoryId) :
                new ObjectParameter("SafeCategoryId", typeof(System.Guid));
    
            var applyedParameter = applyed.HasValue ?
                new ObjectParameter("Applyed", applyed) :
                new ObjectParameter("Applyed", typeof(bool));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SafeDetail_InsertOrUpdate", flagParameter, safeDetailIdParameter, postIdParameter, safeCategoryIdParameter, applyedParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_TypeOfCar_DELETE(Nullable<System.Guid> typeOfCarID)
        {
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_TypeOfCar_DELETE", typeOfCarIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_TypeOfCar_GetAll_Result> WEB_CARONLINE_SP_TypeOfCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_TypeOfCar_GetAll_Result>("WEB_CARONLINE_SP_TypeOfCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_TypeOfCar_GetAll2_Result> WEB_CARONLINE_SP_TypeOfCar_GetAll2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_TypeOfCar_GetAll2_Result>("WEB_CARONLINE_SP_TypeOfCar_GetAll2");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_TypeOfCar_GetByID_Result> WEB_CARONLINE_SP_TypeOfCar_GetByID(Nullable<System.Guid> typeOfCarID)
        {
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_TypeOfCar_GetByID_Result>("WEB_CARONLINE_SP_TypeOfCar_GetByID", typeOfCarIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_TypeOfCar_INSERT(Nullable<System.Guid> typeOfCarID, string typeName, Nullable<System.Guid> companyID, Nullable<bool> status, string description, Nullable<System.Guid> designID)
        {
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            var typeNameParameter = typeName != null ?
                new ObjectParameter("TypeName", typeName) :
                new ObjectParameter("TypeName", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var designIDParameter = designID.HasValue ?
                new ObjectParameter("DesignID", designID) :
                new ObjectParameter("DesignID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_TypeOfCar_INSERT", typeOfCarIDParameter, typeNameParameter, companyIDParameter, statusParameter, descriptionParameter, designIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_TypeOfCar_UPDATE(Nullable<System.Guid> typeOfCarID, string typeName, Nullable<System.Guid> companyID, Nullable<bool> status, string description, Nullable<System.Guid> designID)
        {
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            var typeNameParameter = typeName != null ?
                new ObjectParameter("TypeName", typeName) :
                new ObjectParameter("TypeName", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var designIDParameter = designID.HasValue ?
                new ObjectParameter("DesignID", designID) :
                new ObjectParameter("DesignID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_TypeOfCar_UPDATE", typeOfCarIDParameter, typeNameParameter, companyIDParameter, statusParameter, descriptionParameter, designIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_UtilitiesCategory_Delete(Nullable<System.Guid> utilitiesCategoryId)
        {
            var utilitiesCategoryIdParameter = utilitiesCategoryId.HasValue ?
                new ObjectParameter("UtilitiesCategoryId", utilitiesCategoryId) :
                new ObjectParameter("UtilitiesCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_UtilitiesCategory_Delete", utilitiesCategoryIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_UtilitiesCategory_GetAll_Result> WEB_CARONLINE_SP_UtilitiesCategory_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_UtilitiesCategory_GetAll_Result>("WEB_CARONLINE_SP_UtilitiesCategory_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_UtilitiesCategory_GetById_Result> WEB_CARONLINE_SP_UtilitiesCategory_GetById(Nullable<System.Guid> utilitiesCategoryId)
        {
            var utilitiesCategoryIdParameter = utilitiesCategoryId.HasValue ?
                new ObjectParameter("UtilitiesCategoryId", utilitiesCategoryId) :
                new ObjectParameter("UtilitiesCategoryId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_UtilitiesCategory_GetById_Result>("WEB_CARONLINE_SP_UtilitiesCategory_GetById", utilitiesCategoryIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_UtilitiesCategory_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> utilitiesCategoryId, string utilitiesCategoryName)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var utilitiesCategoryIdParameter = utilitiesCategoryId.HasValue ?
                new ObjectParameter("UtilitiesCategoryId", utilitiesCategoryId) :
                new ObjectParameter("UtilitiesCategoryId", typeof(System.Guid));
    
            var utilitiesCategoryNameParameter = utilitiesCategoryName != null ?
                new ObjectParameter("UtilitiesCategoryName", utilitiesCategoryName) :
                new ObjectParameter("UtilitiesCategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_UtilitiesCategory_InsertOrUpdate", flagParameter, utilitiesCategoryIdParameter, utilitiesCategoryNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_UtilitiesDetail_Delete(Nullable<System.Guid> utilitiesDetailId)
        {
            var utilitiesDetailIdParameter = utilitiesDetailId.HasValue ?
                new ObjectParameter("UtilitiesDetailId", utilitiesDetailId) :
                new ObjectParameter("UtilitiesDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_UtilitiesDetail_Delete", utilitiesDetailIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_UtilitiesDetail_GetAll_Result> WEB_CARONLINE_SP_UtilitiesDetail_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_UtilitiesDetail_GetAll_Result>("WEB_CARONLINE_SP_UtilitiesDetail_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_UtilitiesDetail_GetById_Result> WEB_CARONLINE_SP_UtilitiesDetail_GetById(Nullable<System.Guid> utilitiesDetailId)
        {
            var utilitiesDetailIdParameter = utilitiesDetailId.HasValue ?
                new ObjectParameter("UtilitiesDetailId", utilitiesDetailId) :
                new ObjectParameter("UtilitiesDetailId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_UtilitiesDetail_GetById_Result>("WEB_CARONLINE_SP_UtilitiesDetail_GetById", utilitiesDetailIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_UtilitiesDetail_InsertOrUpdate(Nullable<bool> flag, Nullable<System.Guid> utilitiesDetailId, Nullable<System.Guid> postId, Nullable<System.Guid> utilitiesCategoryId, Nullable<bool> applyed, Nullable<bool> isDeleted)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("Flag", flag) :
                new ObjectParameter("Flag", typeof(bool));
    
            var utilitiesDetailIdParameter = utilitiesDetailId.HasValue ?
                new ObjectParameter("UtilitiesDetailId", utilitiesDetailId) :
                new ObjectParameter("UtilitiesDetailId", typeof(System.Guid));
    
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            var utilitiesCategoryIdParameter = utilitiesCategoryId.HasValue ?
                new ObjectParameter("UtilitiesCategoryId", utilitiesCategoryId) :
                new ObjectParameter("UtilitiesCategoryId", typeof(System.Guid));
    
            var applyedParameter = applyed.HasValue ?
                new ObjectParameter("Applyed", applyed) :
                new ObjectParameter("Applyed", typeof(bool));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_UtilitiesDetail_InsertOrUpdate", flagParameter, utilitiesDetailIdParameter, postIdParameter, utilitiesCategoryIdParameter, applyedParameter, isDeletedParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_WheelDrive_DELETE(Nullable<System.Guid> wheelDriveId)
        {
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_WheelDrive_DELETE", wheelDriveIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_WheelDrive_GetAll_Result> WEB_CARONLINE_SP_WheelDrive_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_WheelDrive_GetAll_Result>("WEB_CARONLINE_SP_WheelDrive_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_WheelDrive_GetByID_Result> WEB_CARONLINE_SP_WheelDrive_GetByID(Nullable<System.Guid> wheelDriveId)
        {
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_WheelDrive_GetByID_Result>("WEB_CARONLINE_SP_WheelDrive_GetByID", wheelDriveIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_WheelDrive_INSERT(Nullable<System.Guid> wheelDriveId, string wheelDriveName)
        {
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            var wheelDriveNameParameter = wheelDriveName != null ?
                new ObjectParameter("WheelDriveName", wheelDriveName) :
                new ObjectParameter("WheelDriveName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_WheelDrive_INSERT", wheelDriveIdParameter, wheelDriveNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_WheelDrive_UPDATE(Nullable<System.Guid> wheelDriveId, string wheelDriveName)
        {
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            var wheelDriveNameParameter = wheelDriveName != null ?
                new ObjectParameter("WheelDriveName", wheelDriveName) :
                new ObjectParameter("WheelDriveName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_WheelDrive_UPDATE", wheelDriveIdParameter, wheelDriveNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Post_Delete(Nullable<System.Guid> postId)
        {
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Post_Delete", postIdParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Post_GetAll_Result> WEB_CARONLINE_SP_Post_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Post_GetAll_Result>("WEB_CARONLINE_SP_Post_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_Post_GetByPostId_Result> WEB_CARONLINE_SP_Post_GetByPostId(Nullable<System.Guid> postId)
        {
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_Post_GetByPostId_Result>("WEB_CARONLINE_SP_Post_GetByPostId", postIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Post_Insert(Nullable<System.Guid> accountID, Nullable<System.Guid> administratorID, Nullable<bool> approved, Nullable<System.DateTime> approvedDay, Nullable<System.Guid> carGearId, Nullable<int> carPrice, Nullable<System.Guid> carStatusID, Nullable<System.Guid> exteriorColorID, Nullable<System.Guid> fuelID, Nullable<System.Guid> furnitureColorID, Nullable<bool> isDeleted, string kmWent, Nullable<System.DateTime> lastContactDay, Nullable<System.Guid> madeInId, string note, Nullable<System.Guid> numberOfDoorId, Nullable<System.Guid> numberOfSeatId, string postContent, Nullable<System.DateTime> postDay, Nullable<System.Guid> postId, string postTitle, Nullable<int> producedYear, Nullable<System.Guid> saleStatusCarID, Nullable<System.Guid> typeOfCarID, Nullable<System.DateTime> updatePostDay, Nullable<System.Guid> wheelDriveId)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            var administratorIDParameter = administratorID.HasValue ?
                new ObjectParameter("AdministratorID", administratorID) :
                new ObjectParameter("AdministratorID", typeof(System.Guid));
    
            var approvedParameter = approved.HasValue ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(bool));
    
            var approvedDayParameter = approvedDay.HasValue ?
                new ObjectParameter("ApprovedDay", approvedDay) :
                new ObjectParameter("ApprovedDay", typeof(System.DateTime));
    
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            var carPriceParameter = carPrice.HasValue ?
                new ObjectParameter("CarPrice", carPrice) :
                new ObjectParameter("CarPrice", typeof(int));
    
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            var exteriorColorIDParameter = exteriorColorID.HasValue ?
                new ObjectParameter("ExteriorColorID", exteriorColorID) :
                new ObjectParameter("ExteriorColorID", typeof(System.Guid));
    
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            var furnitureColorIDParameter = furnitureColorID.HasValue ?
                new ObjectParameter("FurnitureColorID", furnitureColorID) :
                new ObjectParameter("FurnitureColorID", typeof(System.Guid));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var kmWentParameter = kmWent != null ?
                new ObjectParameter("KmWent", kmWent) :
                new ObjectParameter("KmWent", typeof(string));
    
            var lastContactDayParameter = lastContactDay.HasValue ?
                new ObjectParameter("LastContactDay", lastContactDay) :
                new ObjectParameter("LastContactDay", typeof(System.DateTime));
    
            var madeInIdParameter = madeInId.HasValue ?
                new ObjectParameter("MadeInId", madeInId) :
                new ObjectParameter("MadeInId", typeof(System.Guid));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            var postContentParameter = postContent != null ?
                new ObjectParameter("PostContent", postContent) :
                new ObjectParameter("PostContent", typeof(string));
    
            var postDayParameter = postDay.HasValue ?
                new ObjectParameter("PostDay", postDay) :
                new ObjectParameter("PostDay", typeof(System.DateTime));
    
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            var postTitleParameter = postTitle != null ?
                new ObjectParameter("PostTitle", postTitle) :
                new ObjectParameter("PostTitle", typeof(string));
    
            var producedYearParameter = producedYear.HasValue ?
                new ObjectParameter("ProducedYear", producedYear) :
                new ObjectParameter("ProducedYear", typeof(int));
    
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            var updatePostDayParameter = updatePostDay.HasValue ?
                new ObjectParameter("UpdatePostDay", updatePostDay) :
                new ObjectParameter("UpdatePostDay", typeof(System.DateTime));
    
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Post_Insert", accountIDParameter, administratorIDParameter, approvedParameter, approvedDayParameter, carGearIdParameter, carPriceParameter, carStatusIDParameter, exteriorColorIDParameter, fuelIDParameter, furnitureColorIDParameter, isDeletedParameter, kmWentParameter, lastContactDayParameter, madeInIdParameter, noteParameter, numberOfDoorIdParameter, numberOfSeatIdParameter, postContentParameter, postDayParameter, postIdParameter, postTitleParameter, producedYearParameter, saleStatusCarIDParameter, typeOfCarIDParameter, updatePostDayParameter, wheelDriveIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_Post_Update(Nullable<System.Guid> accountID, Nullable<System.Guid> administratorID, Nullable<bool> approved, Nullable<System.DateTime> approvedDay, Nullable<System.Guid> carGearId, Nullable<int> carPrice, Nullable<System.Guid> carStatusID, Nullable<System.Guid> exteriorColorID, Nullable<System.Guid> fuelID, Nullable<System.Guid> furnitureColorID, Nullable<bool> isDeleted, string kmWent, Nullable<System.DateTime> lastContactDay, Nullable<System.Guid> madeInId, string note, Nullable<System.Guid> numberOfDoorId, Nullable<System.Guid> numberOfSeatId, string postContent, Nullable<System.DateTime> postDay, Nullable<System.Guid> postId, string postTitle, Nullable<int> producedYear, Nullable<System.Guid> saleStatusCarID, Nullable<System.Guid> typeOfCarID, Nullable<System.DateTime> updatePostDay, Nullable<System.Guid> wheelDriveId)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(System.Guid));
    
            var administratorIDParameter = administratorID.HasValue ?
                new ObjectParameter("AdministratorID", administratorID) :
                new ObjectParameter("AdministratorID", typeof(System.Guid));
    
            var approvedParameter = approved.HasValue ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(bool));
    
            var approvedDayParameter = approvedDay.HasValue ?
                new ObjectParameter("ApprovedDay", approvedDay) :
                new ObjectParameter("ApprovedDay", typeof(System.DateTime));
    
            var carGearIdParameter = carGearId.HasValue ?
                new ObjectParameter("CarGearId", carGearId) :
                new ObjectParameter("CarGearId", typeof(System.Guid));
    
            var carPriceParameter = carPrice.HasValue ?
                new ObjectParameter("CarPrice", carPrice) :
                new ObjectParameter("CarPrice", typeof(int));
    
            var carStatusIDParameter = carStatusID.HasValue ?
                new ObjectParameter("CarStatusID", carStatusID) :
                new ObjectParameter("CarStatusID", typeof(System.Guid));
    
            var exteriorColorIDParameter = exteriorColorID.HasValue ?
                new ObjectParameter("ExteriorColorID", exteriorColorID) :
                new ObjectParameter("ExteriorColorID", typeof(System.Guid));
    
            var fuelIDParameter = fuelID.HasValue ?
                new ObjectParameter("FuelID", fuelID) :
                new ObjectParameter("FuelID", typeof(System.Guid));
    
            var furnitureColorIDParameter = furnitureColorID.HasValue ?
                new ObjectParameter("FurnitureColorID", furnitureColorID) :
                new ObjectParameter("FurnitureColorID", typeof(System.Guid));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var kmWentParameter = kmWent != null ?
                new ObjectParameter("KmWent", kmWent) :
                new ObjectParameter("KmWent", typeof(string));
    
            var lastContactDayParameter = lastContactDay.HasValue ?
                new ObjectParameter("LastContactDay", lastContactDay) :
                new ObjectParameter("LastContactDay", typeof(System.DateTime));
    
            var madeInIdParameter = madeInId.HasValue ?
                new ObjectParameter("MadeInId", madeInId) :
                new ObjectParameter("MadeInId", typeof(System.Guid));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var numberOfDoorIdParameter = numberOfDoorId.HasValue ?
                new ObjectParameter("NumberOfDoorId", numberOfDoorId) :
                new ObjectParameter("NumberOfDoorId", typeof(System.Guid));
    
            var numberOfSeatIdParameter = numberOfSeatId.HasValue ?
                new ObjectParameter("NumberOfSeatId", numberOfSeatId) :
                new ObjectParameter("NumberOfSeatId", typeof(System.Guid));
    
            var postContentParameter = postContent != null ?
                new ObjectParameter("PostContent", postContent) :
                new ObjectParameter("PostContent", typeof(string));
    
            var postDayParameter = postDay.HasValue ?
                new ObjectParameter("PostDay", postDay) :
                new ObjectParameter("PostDay", typeof(System.DateTime));
    
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(System.Guid));
    
            var postTitleParameter = postTitle != null ?
                new ObjectParameter("PostTitle", postTitle) :
                new ObjectParameter("PostTitle", typeof(string));
    
            var producedYearParameter = producedYear.HasValue ?
                new ObjectParameter("ProducedYear", producedYear) :
                new ObjectParameter("ProducedYear", typeof(int));
    
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            var typeOfCarIDParameter = typeOfCarID.HasValue ?
                new ObjectParameter("TypeOfCarID", typeOfCarID) :
                new ObjectParameter("TypeOfCarID", typeof(System.Guid));
    
            var updatePostDayParameter = updatePostDay.HasValue ?
                new ObjectParameter("UpdatePostDay", updatePostDay) :
                new ObjectParameter("UpdatePostDay", typeof(System.DateTime));
    
            var wheelDriveIdParameter = wheelDriveId.HasValue ?
                new ObjectParameter("WheelDriveId", wheelDriveId) :
                new ObjectParameter("WheelDriveId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_Post_Update", accountIDParameter, administratorIDParameter, approvedParameter, approvedDayParameter, carGearIdParameter, carPriceParameter, carStatusIDParameter, exteriorColorIDParameter, fuelIDParameter, furnitureColorIDParameter, isDeletedParameter, kmWentParameter, lastContactDayParameter, madeInIdParameter, noteParameter, numberOfDoorIdParameter, numberOfSeatIdParameter, postContentParameter, postDayParameter, postIdParameter, postTitleParameter, producedYearParameter, saleStatusCarIDParameter, typeOfCarIDParameter, updatePostDayParameter, wheelDriveIdParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SaleStatusCar_Delete(Nullable<System.Guid> saleStatusCarID)
        {
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SaleStatusCar_Delete", saleStatusCarIDParameter);
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SaleStatusCar_GetAll_Result> WEB_CARONLINE_SP_SaleStatusCar_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SaleStatusCar_GetAll_Result>("WEB_CARONLINE_SP_SaleStatusCar_GetAll");
        }
    
        public virtual ObjectResult<WEB_CARONLINE_SP_SaleStatusCar_GetBySaleStatusCarID_Result> WEB_CARONLINE_SP_SaleStatusCar_GetBySaleStatusCarID(Nullable<System.Guid> saleStatusCarID)
        {
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_CARONLINE_SP_SaleStatusCar_GetBySaleStatusCarID_Result>("WEB_CARONLINE_SP_SaleStatusCar_GetBySaleStatusCarID", saleStatusCarIDParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SaleStatusCar_Insert(Nullable<bool> isDeleted, Nullable<System.Guid> saleStatusCarID, string saleStatusCarName)
        {
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            var saleStatusCarNameParameter = saleStatusCarName != null ?
                new ObjectParameter("SaleStatusCarName", saleStatusCarName) :
                new ObjectParameter("SaleStatusCarName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SaleStatusCar_Insert", isDeletedParameter, saleStatusCarIDParameter, saleStatusCarNameParameter);
        }
    
        public virtual int WEB_CARONLINE_SP_SaleStatusCar_Update(Nullable<bool> isDeleted, Nullable<System.Guid> saleStatusCarID, string saleStatusCarName)
        {
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var saleStatusCarIDParameter = saleStatusCarID.HasValue ?
                new ObjectParameter("SaleStatusCarID", saleStatusCarID) :
                new ObjectParameter("SaleStatusCarID", typeof(System.Guid));
    
            var saleStatusCarNameParameter = saleStatusCarName != null ?
                new ObjectParameter("SaleStatusCarName", saleStatusCarName) :
                new ObjectParameter("SaleStatusCarName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_CARONLINE_SP_SaleStatusCar_Update", isDeletedParameter, saleStatusCarIDParameter, saleStatusCarNameParameter);
        }
    }
}
