//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.ENTITYMODELS.DATA
{
    using System;
    
    public partial class WEB_CARONLINE_SP_Post_GetByDateCreate_Paging_Result
    {
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<int> CarPrice { get; set; }
        public Nullable<System.Guid> CarStatusID { get; set; }
        public string KmWent { get; set; }
        public Nullable<System.DateTime> LastContactDay { get; set; }
        public Nullable<System.Guid> MadeInId { get; set; }
        public string Note { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.DateTime> PostDay { get; set; }
        public System.Guid PostId { get; set; }
        public string PostTitle { get; set; }
        public Nullable<System.Guid> SaleStatusCarID { get; set; }
        public Nullable<System.Guid> TypeOfCarID { get; set; }
        public string Address_AccountPostJoin { get; set; }
        public string FullName_AccountPostJoin { get; set; }
        public string Mobile_AccountPostJoin { get; set; }
        public Nullable<long> RC { get; set; }
        public long Carcode { get; set; }
        public string Avatar { get; set; }
    }
}
